// MCP tool feature tests driven over the real MCP unix socket.
// Full tool coverage (social, routes, tasks, invites, ACL, inspection,
// web-routes) lives in integration_mcp_test.go (generated by opus agent).
// This file anchors the set-observe-window path as a smoke canary.
package tests

import (
	"testing"
)

func TestFeature_MCPTools(t *testing.T) {
	// set_observe_window persists via the real MCP socket → ipc → store path.
	t.Run("set-observe-window", func(t *testing.T) {
		h := newMCPHarness(t, "world/sub")
		res := h.call(t, "set_observe_window", map[string]any{"messages": float64(8), "chars": float64(400)})
		if res.IsError {
			t.Fatalf("set_observe_window: %+v", res.Content)
		}
		if m, c := h.S.GroupObserveWindow("world/sub"); m != 8 || c != 400 {
			t.Fatalf("window = %d,%d want 8,400", m, c)
		}
	})
}
