package store

import (
	"fmt"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/kronael/arizuko/core"
)

func TestOpenMemAndMigrate(t *testing.T) {
	s, err := OpenMem()
	if err != nil {
		t.Fatal(err)
	}
	defer s.Close()
}

// Regression: SQLITE_BUSY blasted gated/discd on sloth because the DSN
// used mattn-style `_busy_timeout=5000`, which modernc.org/sqlite
// silently ignores. Two writers against the same file file must
// serialize via busy_timeout, not bubble BUSY up to callers.
func TestPutMessageNoBusyUnderConcurrentWriters(t *testing.T) {
	dir := t.TempDir()
	a, err := Open(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer a.Close()
	b, err := Open(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer b.Close()

	const writers = 8
	const perWriter = 25
	var wg sync.WaitGroup
	errs := make(chan error, writers*perWriter)
	now := time.Now()
	for w := 0; w < writers; w++ {
		wg.Add(1)
		s := a
		if w%2 == 1 {
			s = b
		}
		go func(w int, s *Store) {
			defer wg.Done()
			for i := 0; i < perWriter; i++ {
				err := s.PutMessage(core.Message{
					ID:        fmt.Sprintf("m-%d-%d", w, i),
					ChatJID:   "tg:1",
					Sender:    "user",
					Content:   "x",
					Timestamp: now,
				})
				if err != nil {
					errs <- err
				}
			}
		}(w, s)
	}
	wg.Wait()
	close(errs)
	for err := range errs {
		t.Fatalf("PutMessage: %v", err)
	}
}

func TestPutAndGetMessage(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	now := time.Now()
	msg := core.Message{
		ID:        "m1",
		ChatJID:   "tg:123",
		Sender:    "alice",
		Name:      "Alice",
		Content:   "hello",
		Timestamp: now,
	}
	if err := s.PutMessage(msg); err != nil {
		t.Fatal(err)
	}

	msgs, hi, err := s.NewMessages([]string{"tg:123"}, now.Add(-time.Second), "Bot")
	if err != nil {
		t.Fatal(err)
	}
	if len(msgs) != 1 {
		t.Fatalf("expected 1 message, got %d", len(msgs))
	}
	if msgs[0].Content != "hello" {
		t.Fatalf("expected 'hello', got %q", msgs[0].Content)
	}
	if hi.Before(now) {
		t.Fatal("high-water mark should be >= message timestamp")
	}
}

func TestBotMessagesFiltered(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	now := time.Now()
	s.PutMessage(core.Message{
		ID: "m1", ChatJID: "tg:1", Sender: "user", Content: "hi",
		Timestamp: now,
	})
	s.PutMessage(core.Message{
		ID: "m2", ChatJID: "tg:1", Sender: "Andy", Content: "reply",
		Timestamp: now.Add(time.Second), BotMsg: true,
	})

	msgs, _, _ := s.NewMessages([]string{"tg:1"}, now.Add(-time.Second), "Andy")
	if len(msgs) != 1 {
		t.Fatalf("expected 1 (bot filtered), got %d", len(msgs))
	}
}

func TestGroupCRUD(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	g := core.Group{
		Folder:  "main",
		AddedAt: time.Now(),
	}
	if err := s.PutGroup(g); err != nil {
		t.Fatal(err)
	}

	all := s.AllGroups()
	if len(all) != 1 {
		t.Fatalf("expected 1 group, got %d", len(all))
	}
	if _, ok := all["main"]; !ok {
		t.Fatal("group not found by folder key")
	}
}

func TestGroupSlinkTokenAutoGenerated(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	g := core.Group{Folder: "main", AddedAt: time.Now()}
	if err := s.PutGroup(g); err != nil {
		t.Fatal(err)
	}
	got, ok := s.GroupBySlinkToken("")
	if ok {
		t.Fatal("empty token should not match")
	}
	all := s.AllGroups()
	tok := all["main"].SlinkToken
	if tok == "" {
		t.Fatal("slink token not auto-generated")
	}
	if len(tok) < 16 {
		t.Fatalf("token too short: %d: %q", len(tok), tok)
	}
	got, ok = s.GroupBySlinkToken(tok)
	if !ok || got.Folder != "main" {
		t.Fatal("GroupBySlinkToken lookup failed")
	}
}

func TestSessionState(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	s.SetSession("main", "", "sess-1")
	if got, ok := s.GetSession("main", ""); !ok || got != "sess-1" {
		t.Fatalf("expected sess-1, got %q", got)
	}

	s.DeleteSession("main", "")
	if got, _ := s.GetSession("main", ""); got != "" {
		t.Fatalf("expected empty after delete, got %q", got)
	}
}

func TestRouterState(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	s.SetState("cursor", "2024-01-01")
	if got := s.GetState("cursor"); got != "2024-01-01" {
		t.Fatalf("expected '2024-01-01', got %q", got)
	}
}

func TestSystemMessages(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	s.EnqueueSysMsg("main", "gateway", "new-session", "")
	s.EnqueueSysMsg("main", "gateway", "new-day", "")

	xml := s.FlushSysMsgs("main")
	if xml == "" {
		t.Fatal("expected non-empty XML")
	}
	// Spec Y-system-messages: tag must be <system>, not <system_message>
	if !strings.Contains(xml, "<system ") {
		t.Errorf("expected <system> tag, got: %s", xml)
	}
	if strings.Contains(xml, "<system_message") {
		t.Errorf("unexpected <system_message> tag, got: %s", xml)
	}

	// Second flush should be empty
	xml2 := s.FlushSysMsgs("main")
	if xml2 != "" {
		t.Fatalf("expected empty after flush, got %q", xml2)
	}
}

func TestTaskCRUD(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	now := time.Now()
	next := now.Add(time.Hour)
	task := core.Task{
		ID:      "t1",
		Owner:   "main",
		ChatJID: "tg:1",
		Prompt:  "check weather",
		Cron:    "0 9 * * *",
		NextRun: &next,
		Status:  "active",
		Created: now,
	}
	if err := s.CreateTask(task); err != nil {
		t.Fatal(err)
	}

	got, ok := s.GetTask("t1")
	if !ok {
		t.Fatal("task not found")
	}
	if got.Prompt != "check weather" {
		t.Fatalf("unexpected prompt: %q", got.Prompt)
	}
	if got.Cron != "0 9 * * *" {
		t.Fatalf("cron = %q, want '0 9 * * *'", got.Cron)
	}
	if got.Owner != "main" {
		t.Fatalf("owner = %q, want 'main'", got.Owner)
	}
	if got.Status != "active" {
		t.Fatalf("status = %q, want 'active'", got.Status)
	}
	if got.NextRun == nil {
		t.Fatal("next_run is nil")
	}

	// Update next_run and verify it changed
	past := now.Add(-time.Hour)
	if err := s.UpdateTask("t1", TaskPatch{NextRun: &past}); err != nil {
		t.Fatal("UpdateTask:", err)
	}
	got, ok = s.GetTask("t1")
	if !ok {
		t.Fatal("task not found after update")
	}
	if got.NextRun == nil || got.NextRun.After(now) {
		t.Fatal("next_run should be in the past after update")
	}
}

func TestTaskGetNonexistent(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	_, ok := s.GetTask("does-not-exist")
	if ok {
		t.Fatal("expected not found for nonexistent task")
	}
}

func TestTaskDuplicateID(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	now := time.Now()
	task := core.Task{
		ID: "dup-1", Owner: "main", ChatJID: "tg:1",
		Prompt: "first", Status: "active", Created: now,
	}
	if err := s.CreateTask(task); err != nil {
		t.Fatal(err)
	}
	task.Prompt = "second"
	err := s.CreateTask(task)
	if err == nil {
		t.Fatal("expected error on duplicate task ID")
	}
}

func TestTaskUpdateEmptyPatch(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	now := time.Now()
	s.CreateTask(core.Task{
		ID: "ep-1", Owner: "main", ChatJID: "tg:1",
		Prompt: "test", Status: "active", Created: now,
	})

	// empty patch should be a no-op
	err := s.UpdateTask("ep-1", TaskPatch{})
	if err != nil {
		t.Fatal("empty patch should not error:", err)
	}
	got, ok := s.GetTask("ep-1")
	if !ok {
		t.Fatal("task not found")
	}
	if got.Status != "active" {
		t.Fatalf("status changed after empty patch: %q", got.Status)
	}
}

func TestTaskUpdateNonexistent(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	status := "paused"
	// should not error, just no rows affected
	err := s.UpdateTask("ghost", TaskPatch{Status: &status})
	if err != nil {
		t.Fatal("UpdateTask on nonexistent should not error:", err)
	}
}

func TestTaskUpdateStatus(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	now := time.Now()
	s.CreateTask(core.Task{
		ID: "us-1", Owner: "main", ChatJID: "tg:1",
		Prompt: "test", Status: "active", Created: now,
	})

	status := "paused"
	s.UpdateTask("us-1", TaskPatch{Status: &status})
	got, _ := s.GetTask("us-1")
	if got.Status != "paused" {
		t.Fatalf("status = %q, want 'paused'", got.Status)
	}
}

func TestTaskDelete(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	now := time.Now()
	s.CreateTask(core.Task{
		ID: "del-1", Owner: "main", ChatJID: "tg:1",
		Prompt: "delete me", Status: "active", Created: now,
	})

	if err := s.DeleteTask("del-1"); err != nil {
		t.Fatal("DeleteTask:", err)
	}
	_, ok := s.GetTask("del-1")
	if ok {
		t.Fatal("task still exists after delete")
	}
}

func TestTaskDeleteNonexistent(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	// deleting nonexistent should not error
	if err := s.DeleteTask("ghost"); err != nil {
		t.Fatal("DeleteTask on nonexistent should not error:", err)
	}
}

func TestTaskListByFolder(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	now := time.Now()
	s.CreateTask(core.Task{
		ID: "lf-1", Owner: "alpha", ChatJID: "tg:1",
		Prompt: "alpha task", Status: "active", Created: now,
	})
	s.CreateTask(core.Task{
		ID: "lf-2", Owner: "beta", ChatJID: "tg:2",
		Prompt: "beta task", Status: "active", Created: now.Add(time.Second),
	})
	s.CreateTask(core.Task{
		ID: "lf-3", Owner: "alpha", ChatJID: "tg:3",
		Prompt: "alpha task 2", Status: "active", Created: now.Add(2 * time.Second),
	})

	// non-root: filter by folder
	alpha := s.ListTasks("alpha", false)
	if len(alpha) != 2 {
		t.Fatalf("expected 2 alpha tasks, got %d", len(alpha))
	}

	beta := s.ListTasks("beta", false)
	if len(beta) != 1 {
		t.Fatalf("expected 1 beta task, got %d", len(beta))
	}

	// root: all tasks
	all := s.ListTasks("", true)
	if len(all) != 3 {
		t.Fatalf("expected 3 total tasks, got %d", len(all))
	}
}

func TestTaskListEmpty(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	tasks := s.ListTasks("main", false)
	if len(tasks) != 0 {
		t.Fatalf("expected 0 tasks, got %d", len(tasks))
	}

	all := s.ListTasks("", true)
	if len(all) != 0 {
		t.Fatalf("expected 0 tasks (root), got %d", len(all))
	}
}

func TestTaskOneShotNoCron(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	now := time.Now()
	next := now.Add(time.Hour)
	s.CreateTask(core.Task{
		ID: "os-1", Owner: "main", ChatJID: "tg:1",
		Prompt: "run once", NextRun: &next,
		Status: "active", Created: now,
	})

	got, ok := s.GetTask("os-1")
	if !ok {
		t.Fatal("task not found")
	}
	if got.Cron != "" {
		t.Fatalf("cron should be empty for one-shot, got %q", got.Cron)
	}
}

func TestPutMessageAttachmentsRoundTrip(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	atts := `[{"mime":"image/jpeg","filename":"photo.jpg","url":"http://teled:9001/files/abc","size":1024}]`
	now := time.Now()
	if err := s.PutMessage(core.Message{
		ID: "att1", ChatJID: "tg:1", Sender: "user",
		Content: "look at this", Timestamp: now, Attachments: atts,
	}); err != nil {
		t.Fatal(err)
	}

	msgs, _, err := s.NewMessages([]string{"tg:1"}, now.Add(-time.Second), "Bot")
	if err != nil {
		t.Fatal(err)
	}
	if len(msgs) != 1 {
		t.Fatalf("expected 1 message, got %d", len(msgs))
	}
	if msgs[0].Attachments != atts {
		t.Errorf("attachments = %q, want %q", msgs[0].Attachments, atts)
	}
}

func TestEnrichMessage(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	atts := `[{"mime":"audio/ogg","filename":"voice.ogg","url":"http://teled:9001/files/xyz","size":512}]`
	now := time.Now()
	s.PutMessage(core.Message{
		ID: "enr1", ChatJID: "tg:1", Sender: "user",
		Content: "[Voice message]", Timestamp: now, Attachments: atts,
	})

	if err := s.EnrichMessage("enr1", "[Voice message]\n<attachment path=\"/groups/main/media/voice.ogg\" mime=\"audio/ogg\" filename=\"voice.ogg\" transcript=\"hello world\"/>"); err != nil {
		t.Fatal(err)
	}

	msgs, _, _ := s.NewMessages([]string{"tg:1"}, now.Add(-time.Second), "Bot")
	if len(msgs) != 1 {
		t.Fatalf("expected 1 message, got %d", len(msgs))
	}
	if msgs[0].Attachments != "" {
		t.Errorf("attachments should be cleared after enrich, got %q", msgs[0].Attachments)
	}
	if !strings.Contains(msgs[0].Content, "<attachment") {
		t.Errorf("enriched content should contain attachment XML, got %q", msgs[0].Content)
	}
}

// Agent output messages (is_bot_message=1) must not leak into MessagesSince.
func TestAgentOutput_ExcludedFromMessagesSince(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	if err := s.PutMessage(core.Message{
		ID: "out-1", ChatJID: "tg:1", Sender: "main",
		Content: "bot reply", Timestamp: time.Now(),
		FromMe: true, BotMsg: true, RoutedTo: "tg:1",
	}); err != nil {
		t.Fatal(err)
	}

	msgs, err := s.MessagesSince("tg:1", time.Time{}, "REDACTED")
	if err != nil {
		t.Fatal(err)
	}
	if len(msgs) != 0 {
		t.Fatalf("agent output leaked into MessagesSince: %+v", msgs)
	}
}

// Agent output with topic must appear in MessagesByTopic for web-chat history.
func TestAgentOutput_WritesTopicAndRoutedTo(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	if err := s.PutMessage(core.Message{
		ID: "out-t1", ChatJID: "web:main", Sender: "main",
		Content: "hi", Timestamp: time.Now(),
		FromMe: true, BotMsg: true, RoutedTo: "web:main",
		Topic: "t1",
	}); err != nil {
		t.Fatal(err)
	}

	msgs, err := s.MessagesByTopic("main", "t1", time.Now(), 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(msgs) != 1 || msgs[0].Topic != "t1" || msgs[0].RoutedTo != "web:main" {
		t.Fatalf("agent output missing topic/routed_to: %+v", msgs)
	}
}

// Inbound messages with empty topic must inherit the chat's sticky topic
// so processWebTopics groups them alongside bot replies under the same topic.
func TestPutMessage_InheritsStickyTopic(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	jid := "web:main"
	if err := s.SetStickyTopic(jid, "support"); err != nil {
		t.Fatal(err)
	}

	if err := s.PutMessage(core.Message{
		ID: "in-1", ChatJID: jid, Sender: "user",
		Content: "help", Timestamp: time.Now(),
	}); err != nil {
		t.Fatal(err)
	}

	msgs, err := s.MessagesByTopic("main", "support", time.Now().Add(time.Second), 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(msgs) != 1 || msgs[0].Topic != "support" {
		t.Fatalf("inbound did not inherit sticky topic: %+v", msgs)
	}
}

// MessagesByThread filters by both jid AND topic; messages from another chat
// or another thread on the same chat must not leak into the result.
func TestMessagesByThread_ScopedByJIDAndTopic(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	now := time.Now()
	rows := []core.Message{
		{ID: "a", ChatJID: "telegram:group/-100", Sender: "u1", Content: "in t1",
			Timestamp: now.Add(-3 * time.Minute), Topic: "t1"},
		{ID: "b", ChatJID: "telegram:group/-100", Sender: "u1", Content: "in t2",
			Timestamp: now.Add(-2 * time.Minute), Topic: "t2"},
		{ID: "c", ChatJID: "telegram:group/-200", Sender: "u1", Content: "other chat t1",
			Timestamp: now.Add(-1 * time.Minute), Topic: "t1"},
	}
	for _, m := range rows {
		if err := s.PutMessage(m); err != nil {
			t.Fatalf("put %s: %v", m.ID, err)
		}
	}

	got, err := s.MessagesByThread("telegram:group/-100", "t1", time.Time{}, 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 || got[0].ID != "a" {
		t.Fatalf("MessagesByThread mis-scoped: %+v", got)
	}
}

func TestChatIsGroup_DefaultsFalse(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	if s.GetChatIsGroup("never-seen") {
		t.Fatal("missing chat should default to single-user (is_group=0)")
	}
}

func TestChatIsGroup_RoundTrip(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	if err := s.SetChatIsGroup("telegram:-100", true); err != nil {
		t.Fatal(err)
	}
	if !s.GetChatIsGroup("telegram:-100") {
		t.Fatal("expected is_group=true after Set")
	}
	if err := s.SetChatIsGroup("telegram:-100", false); err != nil {
		t.Fatal(err)
	}
	if s.GetChatIsGroup("telegram:-100") {
		t.Fatal("expected is_group=false after second Set")
	}
}

func TestChatIsGroup_PreservesOtherCols(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	jid := "telegram:42"
	if err := s.SetStickyGroup(jid, "support"); err != nil {
		t.Fatal(err)
	}
	if err := s.SetChatIsGroup(jid, true); err != nil {
		t.Fatal(err)
	}
	if got := s.GetStickyGroup(jid); got != "support" {
		t.Fatalf("sticky_group lost on is_group upsert: got %q", got)
	}
	if !s.GetChatIsGroup(jid) {
		t.Fatal("is_group not persisted")
	}
}

func TestUserScopesNoRows(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	got := s.UserScopes("nobody")
	if len(got) != 0 {
		t.Fatalf("expected empty slice, got %v", got)
	}
}

func TestUserScopesOperatorViaMembership(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	s.CreateAuthUser("op", "op", "", "Operator")
	if err := s.AddACLRow(core.ACLRow{
		Principal: "role:operator", Action: "*", Scope: "**", Effect: "allow",
	}); err != nil {
		t.Fatal(err)
	}
	if err := s.AddMembership("op", "role:operator", "test"); err != nil {
		t.Fatal(err)
	}
	got := s.UserScopes("op")
	if len(got) != 1 || got[0] != "**" {
		t.Fatalf("expected [**], got %v", got)
	}
}

func TestUserScopesSpecificFolders(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	s.CreateAuthUser("u1", "u1", "", "User One")
	for _, scope := range []string{"alpha", "beta"} {
		if err := s.AddACLRow(core.ACLRow{
			Principal: "u1", Action: "admin", Scope: scope, Effect: "allow",
		}); err != nil {
			t.Fatal(err)
		}
	}
	got := s.UserScopes("u1")
	if len(got) != 2 || got[0] != "alpha" || got[1] != "beta" {
		t.Fatalf("expected [alpha beta], got %v", got)
	}
}

func TestPutMessage_DefaultsStatusToSent(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	now := time.Now()
	if err := s.PutMessage(core.Message{
		ID: "m1", ChatJID: "tg:1", Sender: "user",
		Content: "hi", Timestamp: now,
	}); err != nil {
		t.Fatal(err)
	}
	var status string
	s.db.QueryRow(`SELECT status FROM messages WHERE id = ?`, "m1").Scan(&status)
	if status != core.MessageStatusSent {
		t.Errorf("status = %q, want %q", status, core.MessageStatusSent)
	}
}

func TestPendingOutboundOlderThan_AndMarkDelivered(t *testing.T) {
	s, _ := OpenMem()
	defer s.Close()

	old := time.Now().Add(-time.Minute)
	fresh := time.Now()
	// Pending row from a minute ago: should be returned
	s.PutMessage(core.Message{
		ID: "p1", ChatJID: "tg:1", Sender: "main", Content: "old",
		Timestamp: old, FromMe: true, BotMsg: true, RoutedTo: "tg:1",
		Status: core.MessageStatusPending,
	})
	// Pending row just inserted: too fresh for cutoff=now-30s
	s.PutMessage(core.Message{
		ID: "p2", ChatJID: "tg:1", Sender: "main", Content: "fresh",
		Timestamp: fresh, FromMe: true, BotMsg: true, RoutedTo: "tg:1",
		Status: core.MessageStatusPending,
	})
	// Already-sent row: never returned by the pending scan
	s.PutMessage(core.Message{
		ID: "s1", ChatJID: "tg:1", Sender: "main", Content: "done",
		Timestamp: old, FromMe: true, BotMsg: true, RoutedTo: "tg:1",
		Status: core.MessageStatusSent,
	})

	rows, err := s.PendingOutboundOlderThan(time.Now().Add(-30*time.Second), 50)
	if err != nil {
		t.Fatal(err)
	}
	if len(rows) != 1 || rows[0].ID != "p1" {
		t.Fatalf("expected only p1, got %v", rowIDs(rows))
	}
	if rows[0].Status != core.MessageStatusPending {
		t.Errorf("scanned status = %q, want pending", rows[0].Status)
	}

	if err := s.MarkMessageDelivered("p1", "platform-xyz"); err != nil {
		t.Fatal(err)
	}
	var st, replyID string
	s.db.QueryRow(`SELECT status, COALESCE(reply_to_id,'') FROM messages WHERE id = ?`, "p1").
		Scan(&st, &replyID)
	if st != core.MessageStatusSent || replyID != "platform-xyz" {
		t.Errorf("after MarkMessageDelivered: status=%q reply=%q", st, replyID)
	}

	if err := s.MarkMessageStatus("p2", core.MessageStatusFailed); err != nil {
		t.Fatal(err)
	}
	s.db.QueryRow(`SELECT status FROM messages WHERE id = ?`, "p2").Scan(&st)
	if st != core.MessageStatusFailed {
		t.Errorf("after MarkMessageStatus(failed): status=%q", st)
	}
}

func rowIDs(ms []core.Message) []string {
	out := make([]string, len(ms))
	for i, m := range ms {
		out[i] = m.ID
	}
	return out
}
