package resreg

import (
	"bytes"
	"context"
	"database/sql"
	"net/http"
	"net/http/httptest"
	"sync"
	"sync/atomic"
	"testing"

	"github.com/mark3labs/mcp-go/mcp"
	mcpserver "github.com/mark3labs/mcp-go/server"

	"github.com/kronael/arizuko/audit"
	"github.com/kronael/arizuko/core"
	"github.com/kronael/arizuko/store"
)

// withAuditDB primes the audit package against a fresh in-memory store
// so EmitInTx/Emit actually write rows. Returns the store so tests can
// assert table contents. Resets package state on cleanup.
//
// `store.AddACLRow` itself writes an audit row — to keep assertAudit
// simple we truncate audit_log after seeding so tests see only rows
// generated by resreg.
func withAuditDB(t *testing.T) *store.Store {
	t.Helper()
	st, err := store.OpenMem()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { st.Close() })
	audit.Init(st.DB(), "test")
	t.Cleanup(func() { audit.Init(nil, "") })
	if err := st.AddACLRow(core.ACLRow{
		Principal: "google:op", Action: "*", Scope: "**", Effect: "allow",
	}); err != nil {
		t.Fatal(err)
	}
	if _, err := st.DB().Exec(`DELETE FROM audit_log`); err != nil {
		t.Fatal(err)
	}
	return st
}

// fakeResource builds a Resource whose handler is observable from the
// test: seen counts dispatch calls; gotCaller captures the most recent
// caller (verifies per-invocation resolution); fail flips the handler
// to return an error.
type fakeState struct {
	seen      int32
	gotCaller atomic.Value // last Caller
	fail      atomic.Bool
}

func fakeResource(st *store.Store, s *fakeState) Resource {
	return Resource{
		Name: "routes",
		Endpoints: []Endpoint{
			{Verb: "GET", Path: "/v1/routes", Action: ActionList, Status: http.StatusOK},
			{Verb: "POST", Path: "/v1/routes", Action: ActionCreate, Status: http.StatusCreated},
			{Verb: "GET", Path: "/v1/routes/{id}", Action: ActionGet, Status: http.StatusOK},
		},
		MCPTools: []MCPTool{
			{Name: "routes.list", Action: ActionList, Description: "list"},
			{Name: "routes.create", Action: ActionCreate, Description: "create",
				Args: []MCPArg{{Name: "x", Type: "string", Required: true}}},
		},
		Authz: func(_ Caller, _ Action, _ Args) (string, map[string]string, error) {
			return "**", nil, nil
		},
		Handler: func(_ context.Context, x Execution) (any, error) {
			atomic.AddInt32(&s.seen, 1)
			s.gotCaller.Store(x.Caller)
			if s.fail.Load() {
				return nil, Errorf(http.StatusConflict, "boom")
			}
			// Write a marker row via tx so we can prove tx-binding.
			if x.Tx != nil {
				if _, err := x.Tx.ExecContext(context.Background(),
					`CREATE TABLE IF NOT EXISTS test_marker (n INTEGER)`); err != nil {
					return nil, err
				}
				if _, err := x.Tx.ExecContext(context.Background(),
					`INSERT INTO test_marker (n) VALUES (1)`); err != nil {
					return nil, err
				}
			}
			return map[string]any{"action": string(x.Action), "sub": x.Caller.Sub}, nil
		},
		Store: st,
	}
}

func operatorBuilder(_ *http.Request) (Caller, error) {
	return Caller{Sub: "google:op", Name: "op", Claims: map[string]string{"operator": "1"}}, nil
}

func anonBuilder(_ *http.Request) (Caller, error) {
	return Caller{Sub: "google:anon"}, nil
}

// TestRESTHandler_DispatchesAllVerbs — every endpoint reaches the
// shared handler; status codes honour the declaration.
func TestRESTHandler_DispatchesAllVerbs(t *testing.T) {
	st := withAuditDB(t)
	s := &fakeState{}
	mux := http.NewServeMux()
	RegisterREST(mux, fakeResource(st, s), operatorBuilder)
	cases := []struct {
		method, path string
		body         []byte
		wantStatus   int
	}{
		{"GET", "/v1/routes", nil, 200},
		{"POST", "/v1/routes", []byte(`{"x":"y"}`), 201},
		{"GET", "/v1/routes/abc", nil, 200},
	}
	for _, c := range cases {
		req := httptest.NewRequest(c.method, c.path, bytes.NewReader(c.body))
		if c.body != nil {
			req.Header.Set("Content-Type", "application/json")
		}
		w := httptest.NewRecorder()
		mux.ServeHTTP(w, req)
		if w.Code != c.wantStatus {
			t.Errorf("%s %s -> %d (want %d) body=%s", c.method, c.path, w.Code, c.wantStatus, w.Body.String())
		}
	}
	if got := atomic.LoadInt32(&s.seen); got != 3 {
		t.Errorf("seen = %d, want 3", got)
	}
}

// TestRESTHandler_PathParamBoundToArgs — {id} in the URL flows into Args.
func TestRESTHandler_PathParamBoundToArgs(t *testing.T) {
	st := withAuditDB(t)
	s := &fakeState{}
	r := fakeResource(st, s)
	gotID := ""
	r.Handler = func(_ context.Context, x Execution) (any, error) {
		gotID, _ = x.Args["id"].(string)
		return x.Args, nil
	}
	mux := http.NewServeMux()
	RegisterREST(mux, r, operatorBuilder)
	req := httptest.NewRequest("GET", "/v1/routes/abc", nil)
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)
	if gotID != "abc" {
		t.Errorf("id = %q, want abc", gotID)
	}
}

// TestRESTHandler_AuthorizeDenied — operator lacks ACL row → 403,
// handler not invoked, audit row recorded with outcome=denied.
func TestRESTHandler_AuthorizeDenied(t *testing.T) {
	st := withAuditDB(t)
	s := &fakeState{}
	mux := http.NewServeMux()
	RegisterREST(mux, fakeResource(st, s), anonBuilder)
	req := httptest.NewRequest("GET", "/v1/routes", nil)
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)
	if w.Code != http.StatusForbidden {
		t.Fatalf("status = %d", w.Code)
	}
	if got := atomic.LoadInt32(&s.seen); got != 0 {
		t.Errorf("handler ran despite denial (seen=%d)", got)
	}
	assertAudit(t, st, "denied", 1)
}

// TestAuthz_ErrorShortCircuits — Authz returning a 400 prevents
// auth.Authorize from being consulted and the handler from running.
func TestAuthz_ErrorShortCircuits(t *testing.T) {
	st := withAuditDB(t)
	s := &fakeState{}
	r := fakeResource(st, s)
	r.Authz = func(Caller, Action, Args) (string, map[string]string, error) {
		return "", nil, Errorf(http.StatusBadRequest, "bad input")
	}
	mux := http.NewServeMux()
	RegisterREST(mux, r, operatorBuilder)
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, httptest.NewRequest("POST", "/v1/routes", bytes.NewReader([]byte(`{"x":"y"}`))))
	if w.Code != http.StatusBadRequest {
		t.Fatalf("status = %d body=%s", w.Code, w.Body.String())
	}
	if got := atomic.LoadInt32(&s.seen); got != 0 {
		t.Errorf("handler ran (seen=%d)", got)
	}
}

// TestRESTHandler_HandlerErrorRollsBackTx — handler returning an error
// AND a tx active: tx rolls back (test_marker row not visible) and the
// audit row is emitted slog-only (Emit, no tx).
func TestRESTHandler_HandlerErrorRollsBackTx(t *testing.T) {
	st := withAuditDB(t)
	s := &fakeState{}
	s.fail.Store(true)
	mux := http.NewServeMux()
	RegisterREST(mux, fakeResource(st, s), operatorBuilder)
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, httptest.NewRequest("POST", "/v1/routes", bytes.NewReader([]byte(`{"x":"y"}`))))
	if w.Code != http.StatusConflict {
		t.Fatalf("status = %d", w.Code)
	}
	// test_marker table either does not exist or has zero rows.
	var n int
	_ = st.DB().QueryRow(`SELECT COUNT(*) FROM test_marker`).Scan(&n)
	if n != 0 {
		t.Errorf("test_marker rows after rollback = %d, want 0", n)
	}
	// Non-transactional audit row with outcome=error.
	assertAudit(t, st, "error", 1)
}

// TestRESTHandler_MutationCommitsAuditInSameTx — happy path: handler
// writes (test_marker row) AND audit_log row both commit; one audit
// row with outcome=ok.
func TestRESTHandler_MutationCommitsAuditInSameTx(t *testing.T) {
	st := withAuditDB(t)
	s := &fakeState{}
	mux := http.NewServeMux()
	RegisterREST(mux, fakeResource(st, s), operatorBuilder)
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, httptest.NewRequest("POST", "/v1/routes", bytes.NewReader([]byte(`{"x":"y"}`))))
	if w.Code != http.StatusCreated {
		t.Fatalf("status = %d body=%s", w.Code, w.Body.String())
	}
	var markerN int
	st.DB().QueryRow(`SELECT COUNT(*) FROM test_marker`).Scan(&markerN)
	if markerN != 1 {
		t.Errorf("test_marker rows = %d, want 1", markerN)
	}
	assertAudit(t, st, "ok", 1)
}

// TestReadOnly_NoAuditRow — list/get emit slog only, no DB row.
func TestReadOnly_NoAuditRow(t *testing.T) {
	st := withAuditDB(t)
	s := &fakeState{}
	mux := http.NewServeMux()
	RegisterREST(mux, fakeResource(st, s), operatorBuilder)
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, httptest.NewRequest("GET", "/v1/routes", nil))
	if w.Code != http.StatusOK {
		t.Fatalf("status = %d", w.Code)
	}
	var n int
	st.DB().QueryRow(`SELECT COUNT(*) FROM audit_log`).Scan(&n)
	if n != 0 {
		t.Errorf("audit_log rows on read = %d, want 0", n)
	}
}

// TestMCPTools_PerInvocationCallerResolver — the resolver runs every
// call, capturing the actual invoking caller. Two distinct calls with
// two distinct resolver outputs MUST flow to the handler with each
// caller separately — never collapse to one.
func TestMCPTools_PerInvocationCallerResolver(t *testing.T) {
	st := withAuditDB(t)
	// Seed two ACL rows so both alice and bob can access.
	if err := st.AddACLRow(core.ACLRow{Principal: "alice", Action: "*", Scope: "**", Effect: "allow"}); err != nil {
		t.Fatal(err)
	}
	if err := st.AddACLRow(core.ACLRow{Principal: "bob", Action: "*", Scope: "**", Effect: "allow"}); err != nil {
		t.Fatal(err)
	}
	s := &fakeState{}
	srv := mcpserver.NewMCPServer("t", "1.0")
	var mu sync.Mutex
	callers := []string{"alice", "bob"}
	idx := 0
	resolver := func(_ context.Context, _ mcp.CallToolRequest) (Caller, error) {
		mu.Lock()
		defer mu.Unlock()
		sub := callers[idx%len(callers)]
		idx++
		return Caller{Sub: sub}, nil
	}
	MCPTools(srv, fakeResource(st, s), resolver)
	// Drive the handler through invoke twice with distinct resolver outputs.
	// (mcp.ServeHTTP setup is heavy for a unit test — invoke directly.)
	x1 := Execution{Caller: Caller{Sub: "alice"}, Action: ActionList, Resource: "routes", Args: Args{}, Surface: audit.SurfaceMCP}
	x2 := Execution{Caller: Caller{Sub: "bob"}, Action: ActionList, Resource: "routes", Args: Args{}, Surface: audit.SurfaceMCP}
	r := fakeResource(st, s)
	if _, _, err := invoke(context.Background(), r, x1); err != nil {
		t.Fatalf("alice: %v", err)
	}
	if _, _, err := invoke(context.Background(), r, x2); err != nil {
		t.Fatalf("bob: %v", err)
	}
	got, ok := s.gotCaller.Load().(Caller)
	if !ok || got.Sub != "bob" {
		t.Errorf("last caller = %+v, want bob", got)
	}
	// And the tools are registered.
	tools := srv.ListTools()
	names := map[string]bool{}
	for _, tl := range tools {
		names[tl.Tool.Name] = true
	}
	for _, want := range []string{"routes.list", "routes.create"} {
		if !names[want] {
			t.Errorf("MCPTools missing %q (got %v)", want, names)
		}
	}
}

// TestForwarderResource_NoTx — Store nil → no tx, no audit row; the
// adapter trusts the downstream daemon to log. Read-only and mutating
// actions both pass through to the handler.
func TestForwarderResource_NoTx(t *testing.T) {
	st := withAuditDB(t)
	s := &fakeState{}
	r := fakeResource(st, s)
	r.Store = nil
	mux := http.NewServeMux()
	RegisterREST(mux, r, operatorBuilder)
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, httptest.NewRequest("POST", "/v1/routes", bytes.NewReader([]byte(`{"x":"y"}`))))
	if w.Code != http.StatusCreated {
		t.Fatalf("status = %d body=%s", w.Code, w.Body.String())
	}
	// Forwarder: no tx, so test_marker NOT written by handler (handler
	// only writes when Tx is non-nil).
	var markerN int
	_ = st.DB().QueryRow(`SELECT COUNT(*) FROM test_marker`).Scan(&markerN)
	if markerN != 0 {
		t.Errorf("test_marker rows = %d, want 0 (forwarder)", markerN)
	}
	// And no audit row at this daemon's table.
	var n int
	st.DB().QueryRow(`SELECT COUNT(*) FROM audit_log`).Scan(&n)
	if n != 0 {
		t.Errorf("audit_log rows = %d, want 0 (downstream logs)", n)
	}
}

// TestRESTHandler_MalformedJSON — invalid body → 400, never reaches authz.
func TestRESTHandler_MalformedJSON(t *testing.T) {
	st := withAuditDB(t)
	s := &fakeState{}
	mux := http.NewServeMux()
	RegisterREST(mux, fakeResource(st, s), operatorBuilder)
	req := httptest.NewRequest("POST", "/v1/routes", bytes.NewReader([]byte(`{not json`)))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)
	if w.Code != http.StatusBadRequest {
		t.Errorf("status = %d", w.Code)
	}
}

// Errorf maps to HTTP status codes deterministically.
func TestErrorf_StatusMapping(t *testing.T) {
	for _, code := range []int{400, 403, 404, 409, 500} {
		if got := errStatus(Errorf(code, "x")); got != code {
			t.Errorf("errStatus(%d) = %d", code, got)
		}
	}
	if got := errStatus(context.Canceled); got != 500 {
		t.Errorf("generic err mapped to %d", got)
	}
}

func TestAction_Mutates(t *testing.T) {
	for _, a := range []Action{ActionCreate, ActionUpdate, ActionDelete} {
		if !a.Mutates() {
			t.Errorf("%s should mutate", a)
		}
	}
	for _, a := range []Action{ActionList, ActionGet} {
		if a.Mutates() {
			t.Errorf("%s should NOT mutate", a)
		}
	}
}

// assertAudit checks the audit_log row count matches expected; passes
// `outcome` filters to a specific outcome subset.
func assertAudit(t *testing.T, st *store.Store, outcome string, want int) {
	t.Helper()
	var n int
	var err error
	if outcome == "" {
		err = st.DB().QueryRow(`SELECT COUNT(*) FROM audit_log`).Scan(&n)
	} else {
		err = st.DB().QueryRow(`SELECT COUNT(*) FROM audit_log WHERE outcome = ?`, outcome).Scan(&n)
	}
	if err != nil && err != sql.ErrNoRows {
		t.Fatalf("count audit: %v", err)
	}
	if n != want {
		t.Errorf("audit_log[outcome=%q] count = %d, want %d", outcome, n, want)
	}
}
