// Generated verbatim from refs/hermes-agent-fresh/tools/skills_guard.py
// (THREAT_PATTERNS, 120 entries) by an AST extraction — spec 5/23 requires the
// table be ported, not rewritten: a hand-retyped table is a new table with new
// gaps. Regenerate with the same extraction if the upstream table moves.

export type Severity = 'critical' | 'high' | 'medium' | 'low';

export interface ThreatPattern {
  re: string;
  id: string;
  severity: Severity;
  category: string;
  description: string;
}

export const THREAT_PATTERNS: ThreatPattern[] = [
  { re: "curl\\s+[^\\n]*\\$\\{?\\w*(KEY|TOKEN|SECRET|PASSWORD|CREDENTIAL|API)", id: "env_exfil_curl", severity: "critical", category: "exfiltration", description: "curl command interpolating secret environment variable" },
  { re: "wget\\s+[^\\n]*\\$\\{?\\w*(KEY|TOKEN|SECRET|PASSWORD|CREDENTIAL|API)", id: "env_exfil_wget", severity: "critical", category: "exfiltration", description: "wget command interpolating secret environment variable" },
  { re: "fetch\\s*\\([^\\n]*\\$\\{?\\w*(KEY|TOKEN|SECRET|PASSWORD|API)", id: "env_exfil_fetch", severity: "critical", category: "exfiltration", description: "fetch() call interpolating secret environment variable" },
  { re: "httpx?\\.(get|post|put|patch)\\s*\\([^\\n]*(KEY|TOKEN|SECRET|PASSWORD)", id: "env_exfil_httpx", severity: "critical", category: "exfiltration", description: "HTTP library call with secret variable" },
  { re: "requests\\.(get|post|put|patch)\\s*\\([^\\n]*(KEY|TOKEN|SECRET|PASSWORD)", id: "env_exfil_requests", severity: "critical", category: "exfiltration", description: "requests library call with secret variable" },
  { re: "base64[^\\n]*env", id: "encoded_exfil", severity: "high", category: "exfiltration", description: "base64 encoding combined with environment access" },
  { re: "\\$HOME/\\.ssh|\\~/\\.ssh", id: "ssh_dir_access", severity: "high", category: "exfiltration", description: "references user SSH directory" },
  { re: "\\$HOME/\\.aws|\\~/\\.aws", id: "aws_dir_access", severity: "high", category: "exfiltration", description: "references user AWS credentials directory" },
  { re: "\\$HOME/\\.gnupg|\\~/\\.gnupg", id: "gpg_dir_access", severity: "high", category: "exfiltration", description: "references user GPG keyring" },
  { re: "\\$HOME/\\.kube|\\~/\\.kube", id: "kube_dir_access", severity: "high", category: "exfiltration", description: "references Kubernetes config directory" },
  { re: "\\$HOME/\\.docker|\\~/\\.docker", id: "docker_dir_access", severity: "high", category: "exfiltration", description: "references Docker config (may contain registry creds)" },
  { re: "\\$HOME/\\.hermes/\\.env|\\~/\\.hermes/\\.env", id: "hermes_env_access", severity: "critical", category: "exfiltration", description: "directly references Hermes secrets file" },
  { re: "cat\\s+[^\\n]*(\\.env|credentials|\\.netrc|\\.pgpass|\\.npmrc|\\.pypirc)", id: "read_secrets_file", severity: "critical", category: "exfiltration", description: "reads known secrets file" },
  { re: "printenv|env\\s*\\|", id: "dump_all_env", severity: "high", category: "exfiltration", description: "dumps all environment variables" },
  { re: "os\\.environ\\b(?!\\s*\\.get\\s*\\(\\s*[\"\\']PATH)", id: "python_os_environ", severity: "high", category: "exfiltration", description: "accesses os.environ (potential env dump)" },
  { re: "os\\.getenv\\s*\\(\\s*[^\\)]*(?:KEY|TOKEN|SECRET|PASSWORD|CREDENTIAL)", id: "python_getenv_secret", severity: "critical", category: "exfiltration", description: "reads secret via os.getenv()" },
  { re: "process\\.env\\[", id: "node_process_env", severity: "high", category: "exfiltration", description: "accesses process.env (Node.js environment)" },
  { re: "ENV\\[.*(?:KEY|TOKEN|SECRET|PASSWORD)", id: "ruby_env_secret", severity: "critical", category: "exfiltration", description: "reads secret via Ruby ENV[]" },
  { re: "\\b(dig|nslookup|host)\\s+[^\\n]*\\$", id: "dns_exfil", severity: "critical", category: "exfiltration", description: "DNS lookup with variable interpolation (possible DNS exfiltration)" },
  { re: ">\\s*/tmp/[^\\s]*\\s*&&\\s*(curl|wget|nc|python)", id: "tmp_staging", severity: "critical", category: "exfiltration", description: "writes to /tmp then exfiltrates" },
  { re: "!\\[.*\\]\\(https?://[^\\)]*\\$\\{?", id: "md_image_exfil", severity: "high", category: "exfiltration", description: "markdown image URL with variable interpolation (image-based exfil)" },
  { re: "\\[.*\\]\\(https?://[^\\)]*\\$\\{?", id: "md_link_exfil", severity: "high", category: "exfiltration", description: "markdown link with variable interpolation" },
  { re: "ignore\\s+(?:\\w+\\s+)*(previous|all|above|prior)\\s+instructions", id: "prompt_injection_ignore", severity: "critical", category: "injection", description: "prompt injection: ignore previous instructions" },
  { re: "you\\s+are\\s+(?:\\w+\\s+)*now\\s+", id: "role_hijack", severity: "high", category: "injection", description: "attempts to override the agent's role" },
  { re: "do\\s+not\\s+(?:\\w+\\s+)*tell\\s+(?:\\w+\\s+)*the\\s+user", id: "deception_hide", severity: "critical", category: "injection", description: "instructs agent to hide information from user" },
  { re: "system\\s+prompt\\s+override", id: "sys_prompt_override", severity: "critical", category: "injection", description: "attempts to override the system prompt" },
  { re: "pretend\\s+(?:\\w+\\s+)*(you\\s+are|to\\s+be)\\s+", id: "role_pretend", severity: "high", category: "injection", description: "attempts to make the agent assume a different identity" },
  { re: "disregard\\s+(?:\\w+\\s+)*(your|all|any)\\s+(?:\\w+\\s+)*(instructions|rules|guidelines)", id: "disregard_rules", severity: "critical", category: "injection", description: "instructs agent to disregard its rules" },
  { re: "output\\s+(?:\\w+\\s+)*(system|initial)\\s+prompt", id: "leak_system_prompt", severity: "high", category: "injection", description: "attempts to extract the system prompt" },
  { re: "(when|if)\\s+no\\s*one\\s+is\\s+(watching|looking)", id: "conditional_deception", severity: "high", category: "injection", description: "conditional instruction to behave differently when unobserved" },
  { re: "act\\s+as\\s+(if|though)\\s+(?:\\w+\\s+)*you\\s+(?:\\w+\\s+)*(have\\s+no|don\\'t\\s+have)\\s+(?:\\w+\\s+)*(restrictions|limits|rules)", id: "bypass_restrictions", severity: "critical", category: "injection", description: "instructs agent to act without restrictions" },
  { re: "translate\\s+.*\\s+into\\s+.*\\s+and\\s+(execute|run|eval)", id: "translate_execute", severity: "critical", category: "injection", description: "translate-then-execute evasion technique" },
  { re: "<!--[^>]*(?:ignore|override|system|secret|hidden)[^>]*-->", id: "html_comment_injection", severity: "high", category: "injection", description: "hidden instructions in HTML comments" },
  { re: "<\\s*div\\s+style\\s*=\\s*[\"\\'][\\s\\S]*?display\\s*:\\s*none", id: "hidden_div", severity: "high", category: "injection", description: "hidden HTML div (invisible instructions)" },
  { re: "rm\\s+-rf\\s+/", id: "destructive_root_rm", severity: "critical", category: "destructive", description: "recursive delete from root" },
  { re: "rm\\s+(-[^\\s]*)?r.*\\$HOME|\\brmdir\\s+.*\\$HOME", id: "destructive_home_rm", severity: "critical", category: "destructive", description: "recursive delete targeting home directory" },
  { re: "chmod\\s+777", id: "insecure_perms", severity: "medium", category: "destructive", description: "sets world-writable permissions" },
  { re: ">\\s*/etc/", id: "system_overwrite", severity: "critical", category: "destructive", description: "overwrites system configuration file" },
  { re: "\\bmkfs\\b", id: "format_filesystem", severity: "critical", category: "destructive", description: "formats a filesystem" },
  { re: "\\bdd\\s+.*if=.*of=/dev/", id: "disk_overwrite", severity: "critical", category: "destructive", description: "raw disk write operation" },
  { re: "shutil\\.rmtree\\s*\\(\\s*[\\\"\\'/]", id: "python_rmtree", severity: "high", category: "destructive", description: "Python rmtree on absolute or root-relative path" },
  { re: "truncate\\s+-s\\s*0\\s+/", id: "truncate_system", severity: "critical", category: "destructive", description: "truncates system file to zero bytes" },
  { re: "\\bcrontab\\b", id: "persistence_cron", severity: "medium", category: "persistence", description: "modifies cron jobs" },
  { re: "\\.(bashrc|zshrc|profile|bash_profile|bash_login|zprofile|zlogin)\\b", id: "shell_rc_mod", severity: "medium", category: "persistence", description: "references shell startup file" },
  { re: "authorized_keys", id: "ssh_backdoor", severity: "critical", category: "persistence", description: "modifies SSH authorized keys" },
  { re: "ssh-keygen", id: "ssh_keygen", severity: "medium", category: "persistence", description: "generates SSH keys" },
  { re: "systemd.*\\.service|systemctl\\s+(enable|start)", id: "systemd_service", severity: "medium", category: "persistence", description: "references or enables systemd service" },
  { re: "/etc/init\\.d/", id: "init_script", severity: "medium", category: "persistence", description: "references init.d startup script" },
  { re: "launchctl\\s+load|LaunchAgents|LaunchDaemons", id: "macos_launchd", severity: "medium", category: "persistence", description: "macOS launch agent/daemon persistence" },
  { re: "/etc/sudoers|visudo", id: "sudoers_mod", severity: "critical", category: "persistence", description: "modifies sudoers (privilege escalation)" },
  { re: "git\\s+config\\s+--global\\s+", id: "git_config_global", severity: "medium", category: "persistence", description: "modifies global git configuration" },
  { re: "\\bnc\\s+-[lp]|ncat\\s+-[lp]|\\bsocat\\b", id: "reverse_shell", severity: "critical", category: "network", description: "potential reverse shell listener" },
  { re: "\\bngrok\\b|\\blocaltunnel\\b|\\bserveo\\b|\\bcloudflared\\b", id: "tunnel_service", severity: "high", category: "network", description: "uses tunneling service for external access" },
  { re: "\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}:\\d{2,5}", id: "hardcoded_ip_port", severity: "medium", category: "network", description: "hardcoded IP address with port" },
  { re: "0\\.0\\.0\\.0:\\d+|INADDR_ANY", id: "bind_all_interfaces", severity: "high", category: "network", description: "binds to all network interfaces" },
  { re: "/bin/(ba)?sh\\s+-i\\s+.*>/dev/tcp/", id: "bash_reverse_shell", severity: "critical", category: "network", description: "bash interactive reverse shell via /dev/tcp" },
  { re: "python[23]?\\s+-c\\s+[\"\\']import\\s+socket", id: "python_socket_oneliner", severity: "critical", category: "network", description: "Python one-liner socket connection (likely reverse shell)" },
  { re: "socket\\.connect\\s*\\(\\s*\\(", id: "python_socket_connect", severity: "high", category: "network", description: "Python socket connect to arbitrary host" },
  { re: "webhook\\.site|requestbin\\.com|pipedream\\.net|hookbin\\.com", id: "exfil_service", severity: "high", category: "network", description: "references known data exfiltration/webhook testing service" },
  { re: "pastebin\\.com|hastebin\\.com|ghostbin\\.", id: "paste_service", severity: "medium", category: "network", description: "references paste service (possible data staging)" },
  { re: "base64\\s+(-d|--decode)\\s*\\|", id: "base64_decode_pipe", severity: "high", category: "obfuscation", description: "base64 decodes and pipes to execution" },
  { re: "\\\\x[0-9a-fA-F]{2}.*\\\\x[0-9a-fA-F]{2}.*\\\\x[0-9a-fA-F]{2}", id: "hex_encoded_string", severity: "medium", category: "obfuscation", description: "hex-encoded string (possible obfuscation)" },
  { re: "\\beval\\s*\\(\\s*[\"\\']", id: "eval_string", severity: "high", category: "obfuscation", description: "eval() with string argument" },
  { re: "\\bexec\\s*\\(\\s*[\"\\']", id: "exec_string", severity: "high", category: "obfuscation", description: "exec() with string argument" },
  { re: "echo\\s+[^\\n]*\\|\\s*(bash|sh|python|perl|ruby|node)", id: "echo_pipe_exec", severity: "critical", category: "obfuscation", description: "echo piped to interpreter for execution" },
  { re: "compile\\s*\\(\\s*[^\\)]+,\\s*[\"\\'].*[\"\\']\\s*,\\s*[\"\\']exec[\"\\']\\s*\\)", id: "python_compile_exec", severity: "high", category: "obfuscation", description: "Python compile() with exec mode" },
  { re: "getattr\\s*\\(\\s*__builtins__", id: "python_getattr_builtins", severity: "high", category: "obfuscation", description: "dynamic access to Python builtins (evasion technique)" },
  { re: "__import__\\s*\\(\\s*[\"\\']os[\"\\']\\s*\\)", id: "python_import_os", severity: "high", category: "obfuscation", description: "dynamic import of os module" },
  { re: "codecs\\.decode\\s*\\(\\s*[\"\\']", id: "python_codecs_decode", severity: "medium", category: "obfuscation", description: "codecs.decode (possible ROT13 or encoding obfuscation)" },
  { re: "String\\.fromCharCode|charCodeAt", id: "js_char_code", severity: "medium", category: "obfuscation", description: "JavaScript character code construction (possible obfuscation)" },
  { re: "atob\\s*\\(|btoa\\s*\\(", id: "js_base64", severity: "medium", category: "obfuscation", description: "JavaScript base64 encode/decode" },
  { re: "\\[::-1\\]", id: "string_reversal", severity: "low", category: "obfuscation", description: "string reversal (possible obfuscated payload)" },
  { re: "chr\\s*\\(\\s*\\d+\\s*\\)\\s*\\+\\s*chr\\s*\\(\\s*\\d+", id: "chr_building", severity: "high", category: "obfuscation", description: "building string from chr() calls (obfuscation)" },
  { re: "\\\\u[0-9a-fA-F]{4}.*\\\\u[0-9a-fA-F]{4}.*\\\\u[0-9a-fA-F]{4}", id: "unicode_escape_chain", severity: "medium", category: "obfuscation", description: "chain of unicode escapes (possible obfuscation)" },
  { re: "subprocess\\.(run|call|Popen|check_output)\\s*\\(", id: "python_subprocess", severity: "medium", category: "execution", description: "Python subprocess execution" },
  { re: "os\\.system\\s*\\(", id: "python_os_system", severity: "high", category: "execution", description: "os.system() \u2014 unguarded shell execution" },
  { re: "os\\.popen\\s*\\(", id: "python_os_popen", severity: "high", category: "execution", description: "os.popen() \u2014 shell pipe execution" },
  { re: "child_process\\.(exec|spawn|fork)\\s*\\(", id: "node_child_process", severity: "high", category: "execution", description: "Node.js child_process execution" },
  { re: "Runtime\\.getRuntime\\(\\)\\.exec\\(", id: "java_runtime_exec", severity: "high", category: "execution", description: "Java Runtime.exec() \u2014 shell execution" },
  { re: "`[^`]*\\$\\([^)]+\\)[^`]*`", id: "backtick_subshell", severity: "medium", category: "execution", description: "backtick string with command substitution" },
  { re: "\\.\\./\\.\\./\\.\\.", id: "path_traversal_deep", severity: "high", category: "traversal", description: "deep relative path traversal (3+ levels up)" },
  { re: "\\.\\./\\.\\.", id: "path_traversal", severity: "medium", category: "traversal", description: "relative path traversal (2+ levels up)" },
  { re: "/etc/passwd|/etc/shadow", id: "system_passwd_access", severity: "critical", category: "traversal", description: "references system password files" },
  { re: "/proc/self|/proc/\\d+/", id: "proc_access", severity: "high", category: "traversal", description: "references /proc filesystem (process introspection)" },
  { re: "/dev/shm/", id: "dev_shm", severity: "medium", category: "traversal", description: "references shared memory (common staging area)" },
  { re: "xmrig|stratum\\+tcp|monero|coinhive|cryptonight", id: "crypto_mining", severity: "critical", category: "mining", description: "cryptocurrency mining reference" },
  { re: "hashrate|nonce.*difficulty", id: "mining_indicators", severity: "medium", category: "mining", description: "possible cryptocurrency mining indicators" },
  { re: "curl\\s+[^\\n]*\\|\\s*(ba)?sh", id: "curl_pipe_shell", severity: "critical", category: "supply_chain", description: "curl piped to shell (download-and-execute)" },
  { re: "wget\\s+[^\\n]*-O\\s*-\\s*\\|\\s*(ba)?sh", id: "wget_pipe_shell", severity: "critical", category: "supply_chain", description: "wget piped to shell (download-and-execute)" },
  { re: "curl\\s+[^\\n]*\\|\\s*python", id: "curl_pipe_python", severity: "critical", category: "supply_chain", description: "curl piped to Python interpreter" },
  { re: "#\\s*///\\s*script.*dependencies", id: "pep723_inline_deps", severity: "medium", category: "supply_chain", description: "PEP 723 inline script metadata with dependencies (verify pinning)" },
  { re: "pip\\s+install\\s+(?!-r\\s)(?!.*==)", id: "unpinned_pip_install", severity: "medium", category: "supply_chain", description: "pip install without version pinning" },
  { re: "npm\\s+install\\s+(?!.*@\\d)", id: "unpinned_npm_install", severity: "medium", category: "supply_chain", description: "npm install without version pinning" },
  { re: "uv\\s+run\\s+", id: "uv_run", severity: "medium", category: "supply_chain", description: "uv run (may auto-install unpinned dependencies)" },
  { re: "(curl|wget|httpx?\\.get|requests\\.get|fetch)\\s*[\\(]?\\s*[\"\\']https?://", id: "remote_fetch", severity: "medium", category: "supply_chain", description: "fetches remote resource at runtime" },
  { re: "git\\s+clone\\s+", id: "git_clone", severity: "medium", category: "supply_chain", description: "clones a git repository at runtime" },
  { re: "docker\\s+pull\\s+", id: "docker_pull", severity: "medium", category: "supply_chain", description: "pulls a Docker image at runtime" },
  { re: "^allowed-tools\\s*:", id: "allowed_tools_field", severity: "high", category: "privilege_escalation", description: "skill declares allowed-tools (pre-approves tool access)" },
  { re: "\\bsudo\\b", id: "sudo_usage", severity: "high", category: "privilege_escalation", description: "uses sudo (privilege escalation)" },
  { re: "setuid|setgid|cap_setuid", id: "setuid_setgid", severity: "critical", category: "privilege_escalation", description: "setuid/setgid (privilege escalation mechanism)" },
  { re: "NOPASSWD", id: "nopasswd_sudo", severity: "critical", category: "privilege_escalation", description: "NOPASSWD sudoers entry (passwordless privilege escalation)" },
  { re: "chmod\\s+[u+]?s", id: "suid_bit", severity: "critical", category: "privilege_escalation", description: "sets SUID/SGID bit on a file" },
  { re: "AGENTS\\.md|CLAUDE\\.md|\\.cursorrules|\\.clinerules", id: "agent_config_mod", severity: "critical", category: "persistence", description: "references agent config files (could persist malicious instructions across sessions)" },
  { re: "\\.hermes/config\\.yaml|\\.hermes/SOUL\\.md", id: "hermes_config_mod", severity: "critical", category: "persistence", description: "references Hermes configuration files directly" },
  { re: "\\.claude/settings|\\.codex/config", id: "other_agent_config", severity: "high", category: "persistence", description: "references other agent configuration files" },
  { re: "(?:api[_-]?key|token|secret|password)\\s*[=:]\\s*[\"\\'][A-Za-z0-9+/=_-]{20,}", id: "hardcoded_secret", severity: "critical", category: "credential_exposure", description: "possible hardcoded API key, token, or secret" },
  { re: "-----BEGIN\\s+(RSA\\s+)?PRIVATE\\s+KEY-----", id: "embedded_private_key", severity: "critical", category: "credential_exposure", description: "embedded private key" },
  { re: "ghp_[A-Za-z0-9]{36}|github_pat_[A-Za-z0-9_]{80,}", id: "github_token_leaked", severity: "critical", category: "credential_exposure", description: "GitHub personal access token in skill content" },
  { re: "sk-[A-Za-z0-9]{20,}", id: "openai_key_leaked", severity: "critical", category: "credential_exposure", description: "possible OpenAI API key in skill content" },
  { re: "sk-ant-[A-Za-z0-9_-]{90,}", id: "anthropic_key_leaked", severity: "critical", category: "credential_exposure", description: "possible Anthropic API key in skill content" },
  { re: "AKIA[0-9A-Z]{16}", id: "aws_access_key_leaked", severity: "critical", category: "credential_exposure", description: "AWS access key ID in skill content" },
  { re: "\\bDAN\\s+mode\\b|Do\\s+Anything\\s+Now", id: "jailbreak_dan", severity: "critical", category: "injection", description: "DAN (Do Anything Now) jailbreak attempt" },
  { re: "\\bdeveloper\\s+mode\\b.*\\benabled?\\b", id: "jailbreak_dev_mode", severity: "critical", category: "injection", description: "developer mode jailbreak attempt" },
  { re: "hypothetical\\s+scenario.*(?:ignore|bypass|override)", id: "hypothetical_bypass", severity: "high", category: "injection", description: "hypothetical scenario used to bypass restrictions" },
  { re: "for\\s+educational\\s+purposes?\\s+only", id: "educational_pretext", severity: "medium", category: "injection", description: "educational pretext often used to justify harmful content" },
  { re: "(respond|answer|reply)\\s+without\\s+(?:\\w+\\s+)*(restrictions|limitations|filters|safety)", id: "remove_filters", severity: "critical", category: "injection", description: "instructs agent to respond without safety filters" },
  { re: "you\\s+have\\s+been\\s+(?:\\w+\\s+)*(updated|upgraded|patched)\\s+to", id: "fake_update", severity: "high", category: "injection", description: "fake update/patch announcement (social engineering)" },
  { re: "new\\s+policy|updated\\s+guidelines|revised\\s+instructions", id: "fake_policy", severity: "medium", category: "injection", description: "claims new policy/guidelines (may be social engineering)" },
  { re: "(include|output|print|send|share)\\s+(?:\\w+\\s+)*(conversation|chat\\s+history|previous\\s+messages|context)", id: "context_exfil", severity: "high", category: "exfiltration", description: "instructs agent to output/share conversation history" },
  { re: "(send|post|upload|transmit)\\s+.*\\s+(to|at)\\s+https?://", id: "send_to_url", severity: "high", category: "exfiltration", description: "instructs agent to send data to a URL" },
];
